init
Actable-AI/actableai-lib pull request #227
Opened 2022-09-23 14:44 UTC by MehdiActable

2022-10-14 08:51 UTC, trunghlt commented on actableai/tasks/regression.py
> +        aai_interventional_model = None
nit: let's change to aai_intervention_model to be consistent with other name format

2022-10-17 08:52 UTC, axeng requested changes

2022-10-17 08:52 UTC, axeng commented on actableai/causal/params.py
> +        return MultiTaskElasticNetCV()
I think it would be good to have clearer names, like `create_regressor` instead of `reg`

2022-10-17 08:52 UTC, axeng commented on actableai/causal/predictors.py
> +        ag_predictor,
Why removing the typing here?

2022-10-17 08:52 UTC, axeng commented on actableai/causal/predictors.py
> +        raise NotImplementedError()
Looks like these should be `abstractmethod`, if not then they have nothing to do here

2022-10-17 08:52 UTC, axeng commented on actableai/causal/predictors.py
>  class SKLearnWrapper:
If you have `abstractmethod` you might want the class to be abstract '`ABC`' as well

2022-10-17 08:52 UTC, axeng commented on actableai/data_validation/tests/test_params.py
>              common_causes=["t"],
Is it possible to use clearer column names instead of single letters?

2022-10-17 08:52 UTC, axeng commented on actableai/intervention/model.py
> +class AAIInterventionEffectPredictor:
I think it would be great to add docstring for this class and for its methods

2022-10-17 08:52 UTC, axeng commented on actableai/intervention/model.py
> +        T_type = get_type_special_no_ag(T[self.current_intervention_column])
Variable should not start with a capital letter in python

2022-10-17 08:52 UTC, axeng commented on actableai/intervention/model.py
> +        T0, _, Y, X = self._generate_TYX(df, target_proba, fit=True)
Very confusing variable names

2022-10-17 08:52 UTC, axeng commented on actableai/intervention/model.py
> +        T0, T1, Y, X = self._generate_TYX(df, target_proba, fit=False)
Very confusing variable names

2022-10-17 08:52 UTC, axeng commented on actableai/intervention/model.py
> +                T1=T1.iloc[t1_indices_non_na].values,  # type: ignore
We should not need to ignore typing

2022-10-17 08:52 UTC, axeng commented on actableai/intervention/model.py
> +                        T1=T1.iloc[t1_indices_non_na].values,  # type: ignore
We should not need to ignore typing

2022-10-17 08:52 UTC, axeng commented on actableai/intervention/model.py
> +        return T0, T1, Y, X
Confusing variable names

2022-10-17 08:52 UTC, axeng commented on actableai/intervention/model.py
> +        T0, T1, Y, X = self._generate_TYX(df, None, False)
Confusing variable names

2022-10-17 08:52 UTC, axeng commented on actableai/models/aai_predictor.py
> +    model_version = MODEL_DEPLOYMENT_VERSION
I think it was better without the config file, I think it's harder to maintain this way

2022-10-17 08:52 UTC, axeng commented on actableai/models/config.py
> +MODEL_DEPLOYMENT_VERSION = 3
We should delete that file imo

2022-10-17 08:52 UTC, axeng commented on actableai/models/inference.py
>  class AAIModelInference:
Some docstring for this class could be useful

2022-10-17 08:52 UTC, axeng commented on actableai/models/intervention.py
> +def empty_string_to_nan(df, task_model, intervention_col, new_intervention_col):
Missing docstring + typing

2022-10-17 08:52 UTC, axeng commented on actableai/tasks/intervention.py
> +        # # Should be refactored
Useless change

2022-10-17 08:52 UTC, axeng commented on actableai/tasks/intervention.py
> +        )  # type: ignore # noqa
I think we should not ignore typing

2022-10-17 08:52 UTC, axeng commented on actableai/causal/predictors.py
> +class SKLearnMultilabelWrapper(SKLearnWrapper):
Missing docstring for the class + methods

2022-10-17 08:52 UTC, axeng commented on actableai/causal/predictors.py
> +class SKLearnTabularWrapper(SKLearnWrapper):
Missing docstring for the class + methods

2022-10-17 08:52 UTC, axeng commented on actableai/causal/predictors.py
>  class SKLearnWrapper:
Missing docstring for the class + methods

2022-10-17 12:53 UTC, trunghlt commented on actableai/intervention/model.py
> +    def predict_effect(self, df, target_proba):
please rename to "predict" instead of "predict_effect"

2022-10-17 12:58 UTC, MehdiActable commented on actableai/data_validation/tests/test_params.py
>              common_causes=["t"],
I dont think its neccessary this is just unit testing

2022-10-17 14:43 UTC, MehdiActable commented on actableai/intervention/model.py
> +        T0, _, Y, X = self._generate_TYX(df, target_proba, fit=True)
I think its good to keep them like this. Those values are parameters for econml fit function and I kept those exact same names.

2022-10-17 14:43 UTC, MehdiActable commented on actableai/intervention/model.py
> +        T0, T1, Y, X = self._generate_TYX(df, target_proba, fit=False)
https://github.com/Actable-AI/actableai-lib/pull/227#discussion_r997153745

2022-10-17 14:45 UTC, MehdiActable commented on actableai/intervention/model.py
> +                T1=T1.iloc[t1_indices_non_na].values,  # type: ignore
The typing is badly done for econml. It takes np.ndarray as parameters but is marked as int because of default parameters.
I can delete those comments of course.

2022-10-17 14:45 UTC, MehdiActable commented on actableai/intervention/model.py
> +                        T1=T1.iloc[t1_indices_non_na].values,  # type: ignore
https://github.com/Actable-AI/actableai-lib/pull/227#discussion_r997155772

2022-10-17 14:45 UTC, MehdiActable commented on actableai/intervention/model.py
> +        return T0, T1, Y, X
https://github.com/Actable-AI/actableai-lib/pull/227#discussion_r997153745

2022-10-17 15:40 UTC, axeng requested changes

2022-10-17 15:40 UTC, axeng commented on actableai/causal/predictors.py
> +class SKLearnWrapper(ABC):
Missing some typing in the methods

2022-10-17 15:45 UTC, MehdiActable commented on actableai/causal/params.py
> +    def create_elasticnet():
This is not really part of the intervention. I even think this is unused functions now.

2022-10-24 14:15 UTC, trunghlt approved these changes

2022-10-25 08:28 UTC, axeng approved these changes

2022-10-25 09:32 UTC, merged