New feature: PDP and ICE
Actable-AI/actableai-lib pull request #290
Opened 2023-01-31 13:00 UTC by cnpgs

Implementation of PDP and ICE, including unit tests.

Note: Categorical features are only partially supported; when using return_type='plot', categorical features are converted to numerical - however, the model should also have been trained using the numerical features. Also, categorical features used for two-way PDP may not fully function. 
It is recommended to use scikit-learn >= 1.2 for better support of categorical features, and pass the list of categorical features.

2023-01-31 13:39 UTC, axeng requested changes
Before merging we also need to format the code using `black`

2023-01-31 13:39 UTC, axeng commented on actableai/utils/tests/test_pdp_ice.py
> +  )
instead of using the kwargs you can just do the following:
```
result = regression_task.run(
      df=df_train,
      target="t",
      run_pdp=False,
      run_ice=False,
      model_directory=tmp_path,
      residuals_hyperparameters=unittest_hyperparameters(),
      presets="medium_quality_faster_train",
      prediction_quantile_low=None,
      prediction_quantile_high=None,
      drop_duplicates=False,
      hyperparameters=unittest_hyperparameters(),
      drop_unique=False,
      drop_useless_features=False,
  )
```

2023-01-31 13:39 UTC, axeng commented on actableai/utils/tests/test_pdp_ice.py
> +  )
same here

2023-01-31 13:39 UTC, axeng commented on actableai/utils/categorical_numerical_convert.py
> +    import copy
I believe it's better to have the import outside of the functions when it's possible.
We do that only in the tasks main code because they are run as ray functions.

2023-01-31 13:39 UTC, axeng commented on actableai/utils/categorical_numerical_convert.py
> +    return df.dtypes[df.dtypes != "int64"][df.dtypes != "float64"]
I would suggest using the `get_type_special` from our utils functions, it's more complete and handles more cases.
You can call it this way to have the types of the columns and look for the "category":
```
from actableai.utils import get_type_special

df = ...

for column in df.columns:
    col_type = get_type_special(df[column])
```

The code is here: https://github.com/Actable-AI/actableai-lib/blob/master/actableai/utils/__init__.py#L56

2023-01-31 13:39 UTC, axeng commented on actableai/utils/categorical_numerical_convert.py
> +    import numpy as np
same here, no need to import inside the function

2023-01-31 13:39 UTC, axeng commented on actableai/utils/categorical_numerical_convert.py
> +    df = copy.deepcopy(df_orig)
maybe to avoid doing copies after copies, you can do one copy in the main function and have a `inplace` parameter in the function to know if you need to copy again. Also I would suggest using the `df_orig.copy()` function, I believe the performances can be better.

2023-01-31 13:55 UTC, trunghlt commented on actableai/utils/pdp_ice.py
> +  if ((model_type!='regressor') and (model_type!='classifier')):
I think we can extract this model_type from the model itself. Check model.problem_type

2023-01-31 13:55 UTC, trunghlt commented on actableai/utils/pdp_ice.py
> +  model_sk3.ag_predictor_ = model_sk3.ag_predictor
maybe we should do this inside SKLearnTabularWrapper. Same as below logic.

2023-01-31 13:55 UTC, trunghlt commented on actableai/utils/pdp_ice.py
> +    #s1 = df_train.shape
remove commented code

2023-01-31 13:55 UTC, trunghlt commented on actableai/utils/pdp_ice.py
> +def compute_pdp_ice(model_sk,
if this is not suppposed to be called outside of this module, it should be private (add _ as function prefix => _compute_pdp_ice)

2023-01-31 13:55 UTC, trunghlt commented on actableai/utils/pdp_ice.py
> +  features (list or str, optional): list of feature names/column numbers on which to compute PDP/ICE, or 'all' to use all columns. If only one fetaure is required, its name or column number should be
comment lines are rather long, they shouldn't exceed 80 characters

2023-02-01 07:42 UTC, cnpgs commented on actableai/utils/pdp_ice.py
> +def compute_pdp_ice(model_sk,
Technically it could be used outside of this module; however, there are some checks which are imlemented in the main function, so it would indeed be preferable to keep this as a private function - I have amended accordingly.

2023-02-01 14:36 UTC, axeng requested changes

2023-02-01 14:36 UTC, axeng commented on actableai/utils/categorical_numerical_convert.py
> +    df = df_new.copy()
Maybe let's add the same `inplace` logic here

2023-02-01 14:36 UTC, axeng commented on actableai/utils/pdp_ice.py
> +    model_type = model.predictor._learner.problem_type
you should be able to do `model.problem_type`, see: https://auto.gluon.ai/stable/api/autogluon.predictor.html?highlight=tabularpredictor#autogluon.tabular.TabularPredictor

2023-02-01 14:36 UTC, axeng commented on actableai/causal/predictors.py
> +        if model_type == "regression":
You might want to add the `quantile` model type, which is used when doing a regression

2023-02-01 14:36 UTC, axeng commented on actableai/utils/pdp_ice.py
> +    if model_type not in ["regression", "multiclass", "binary"]:
If it is supported by PDB we should probably add the `quantile` problem type here as well

2023-02-01 14:36 UTC, axeng commented on actableai/utils/pdp_ice.py
> +    ICE=True,
I would suggest not to use capital letters when defining local variables in python

2023-02-01 14:36 UTC, axeng commented on actableai/utils/pdp_ice.py
> +            df_train_copy = df_train.copy()
We might not need to do a copy here, we should add the `inplace` argument here as well, and set it to True when using the function with classification or regression which are doing a copy already, we just need to verify that it's okay to modify it.

2023-02-01 14:36 UTC, axeng commented on actableai/utils/tests/test_categorical_numerical_convert.py
> +    )
Would it be possible to test this with a smaller dataset? With 10-20 samples, it will take a lot of time to download the dataset every time, and `apartments` is not very small.

2023-02-03 08:13 UTC, trunghlt commented on actableai/utils/categorical_numerical_convert.py
> +def convert_categorical_to_num(df, inplace=False):
Please use scikit learn's LabelEncoder instead

2023-02-06 14:54 UTC, axeng approved these changes

2023-02-06 14:54 UTC, axeng commented on actableai/tasks/classification.py
> -        if run_pdp or run_ice:
Not a big deal but you have some unnecessary parenthesis, these are the same things:
- `((run_pdp or run_ice) and (model is not None))`
- `(run_pdp or run_ice) and (model is not None)`
- `(run_pdp or run_ice) and model is not None`

2023-02-06 14:54 UTC, axeng commented on actableai/utils/categorical_numerical_convert.py
> +    d = defaultdict(LabelEncoder)
I think it would be nice to have a clearer variable name

2023-02-06 14:54 UTC, axeng commented on actableai/utils/pdp_ice.py
> +        print("Model wrapped with sklearn wrapper")
I would recommend using logging instead of printing, print will most likely not show up when running with the whole infrastructure, you can use it this way:

```
import logging

logging.info("your message")
```

2023-02-06 14:56 UTC, axeng commented on actableai/tasks/classification.py
> +        if ((run_pdp or run_ice) and (model is not None)):
Not a big deal but you have some unnecessary parenthesis, these are the same things:
- `((run_pdp or run_ice) and (model is not None))`
- `(run_pdp or run_ice) and (model is not None)`
- `(run_pdp or run_ice) and model is not None`

2023-02-07 12:10 UTC, merged