Regression and Classification Hyperparameters
Actable-AI/actableai-lib pull request #319
Opened 2023-03-29 07:49 UTC by cnpgs

Hyperparameter optimisation tuning for regression and classification, similar to time-series forecasting.

2023-04-05 09:18 UTC, axeng requested changes

2023-04-05 09:18 UTC, axeng commented on actableai/tasks/regression.py
> +        num_trials: int = 2,
I think by default we should have much more than this, probably 8

2023-04-05 09:18 UTC, axeng commented on actableai/tasks/tests/test_regression.py
> +        hyperparameters[model_type] = {}
let's just do hyperparameters = {model_type: {}}

2023-04-05 11:33 UTC, cnpgs commented on actableai/regression/models/params/base.py
> +            parameters_selected = cls()._auto_select(
Indeed; I included the brackets because I thought I had an error when omitting them, but I re-ran it and it works fine; now removed.

2023-04-19 13:32 UTC, axeng approved these changes

2023-04-19 13:32 UTC, merged