classification types int => float
Actable-AI/actableai-lib pull request #341
Opened 2023-06-13 15:32 UTC by BlueRexPY

2023-06-13 17:03 UTC, cnpgs requested changes

2023-06-13 17:03 UTC, cnpgs commented on actableai/tasks/classification.py
> +        num_gpus: float,
The number of GPUs should be an integer, and as such should be `int`

2023-06-13 17:03 UTC, cnpgs commented on actableai/tasks/classification.py
> +        num_gpus: float = 0,
The number of GPUs should be an integer, and as such should be `int`

2023-06-13 17:03 UTC, cnpgs commented on actableai/tasks/classification.py
> +        device = "gpu" if num_gpus > 0 else "cpu"
Note that this essentially reverses https://github.com/Actable-AI/actableai-lib/pull/338

2023-06-13 22:36 UTC, BlueRexPY commented on actableai/tasks/classification.py
> +        num_gpus: float,
You are sure? Documentation (https://docs.ray.io/en/latest/ray-core/tasks/using-ray-with-gpus.html#fractional-gpus)

fractional numbers are needed for asynchronous tasks on the same GPU

the number in this case is taken from the config
https://github.com/Actable-AI/actableai-app/blob/master/docker/.env#LL174C1-L174C25


in the code you can also see how often ray using fractional numbers for num_gpus

https://github.com/ray-project/ray/blob/c4d62111d51780afd2a7ec1d68d8bf3dcf90e24d/doc/source/serve/scaling-and-resource-allocation.md?plain=1#L115
https://github.com/ray-project/ray/blob/c4d62111d51780afd2a7ec1d68d8bf3dcf90e24d/rllib/tuned_examples/dqn/atari-dist-dqn.yaml#LL33C17-L33C17
https://github.com/ray-project/ray/blob/c4d62111d51780afd2a7ec1d68d8bf3dcf90e24d/rllib/tuned_examples/dqn/atari-duel-ddqn.yaml#LL37C14-L37C14

2023-06-13 22:38 UTC, BlueRexPY commented on actableai/tasks/classification.py
> +        device = "gpu" if num_gpus > 0 else "cpu"
since now the data is taken from the config, "auto" cannot get into num_gpus

2023-06-14 06:48 UTC, cnpgs commented on actableai/tasks/classification.py
> +        device = "gpu" if num_gpus > 0 else "cpu"
Ah you also modified the backend, this makes more sense now

2023-06-14 19:26 UTC, trunghlt approved these changes

2023-06-15 07:45 UTC, trunghlt approved these changes

2023-06-26 09:24 UTC, trunghlt approved these changes

2023-06-26 13:40 UTC, cnpgs approved these changes

2023-06-26 13:46 UTC, merged